# Generated by Django 5.0.6 on 2024-06-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOn', models.IntegerField()),
                ('timeOff', models.IntegerField()),
            ],
        ),
    ]
